### ISSUE TITLE
求视频资源

### ISSUE THREAD

**Issue by NarcisWithTreasure** [Catigeart/JavaWeb-LectureManagementSystem#1]
大佬，请问有没有UMLChina相关的视频课程资源

**Comment by Catigeart** [comment]
抱歉，没有。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Catigeart/JavaWeb-LectureManagementSystem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月10日(星期五) 凌晨0:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Catigeart/JavaWeb-LectureManagementSystem] 求视频资源 (Issue #1)





 
大佬，请问有没有UMLChina相关的视频课程资源
